### ISSUE TITLE
Configure the padding

### ISSUE THREAD

**Issue by itsmealwin** [haya14busa/vim-keeppad#1]
Hello again and thank you for all of your marvelous addons!

I am currently looking for exactly this kind of plugin and am wondering if I can configure the amount of pixels to be padded on the vim.
For instance, I would like to have 20 pixels padded instead of 10. Is this possible?

Cheers,
Alwin

**Comment by haya14busa** [comment]
It's impossible, at least with current implementation of vim-keeppad.
vim-keeppad adds padding by showing sign column and we cannot change the width of it.

You can use foldcolumn as a padding and change the width, but foldcolumn shows information about fold instead .

**Comment by itsmealwin** [comment]
Hello,

I understand. This was what I feared because I am currently using the "hack" of fold-column to create the padding. Nevertheless, I will close this now. Thank you again for your quick reply!
